-- =====================================================================
-- setup_all.sql — ONE paste for a FRESH Supabase project (amirlwf.ir)
-- Generated by tools/build_setup_all.py — do not edit this file by hand.
--
-- Dashboard -> SQL Editor -> paste ALL of it -> Run.
-- Every part is idempotent: if a statement fails halfway, fix it and run
-- the whole file again (already-applied parts are harmless).
--
-- After this: Authentication -> Users -> create the admin account, then
-- give it the admin flag (see README step 1.4), then fill the three bots
-- in the panel and deploy the Edge Functions.
-- =====================================================================

-- =====================================================================
-- 1/6  schema: tables, RLS, functions, realtime
-- source: supabase/schema.sql
-- =====================================================================
-- ============================================================
-- amirlwf.ir — Supabase schema (run in Dashboard > SQL Editor)
-- Tables: orders, site_content, notifications (+ RLS + Realtime)
-- ============================================================

-- ---------- orders ----------
create table if not exists public.orders (
  id          bigint generated always as identity primary key,
  created_at  timestamptz not null default now(),
  name        text not null check (char_length(name) between 2 and 80),
  phone       text check (phone ~ '^09[0-9]{9}$'),
  email       text check (email is null or email ~ '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
  service     text not null check (service in ('edit', 'web', 'pc')),
  sub_service text,
  description text not null check (char_length(description) between 5 and 2000),
  status      text not null default 'new' check (status in ('new', 'in_progress', 'done')),
  track_token uuid not null,
  source_ip   text,
  source      text not null default 'fa_site' check (source in ('fa_site', 'en_landing')),
  raw_link    text check (raw_link is null or char_length(raw_link) <= 500),
  admin_reply text
);
create index if not exists orders_created_idx on public.orders (created_at desc);
create index if not exists orders_status_idx  on public.orders (status);
create index if not exists orders_ip_idx      on public.orders (source_ip, created_at desc);

-- ---------- site_content (admin-editable key/value JSON) ----------
create table if not exists public.site_content (
  key        text primary key,
  value      jsonb not null,
  updated_at timestamptz not null default now()
);

-- ---------- notifications (one row per dispatched notification) ----------
create table if not exists public.notifications (
  id       bigint generated always as identity primary key,
  order_id bigint references public.orders (id) on delete cascade,
  channel  text not null,               -- site | telegram | whatsapp | rubika
  payload  jsonb,
  sent_at  timestamptz not null default now()
);
create index if not exists notifications_order_idx on public.notifications (order_id);

-- ============================================================
-- Row Level Security
-- ============================================================
alter table public.orders        enable row level security;
alter table public.site_content  enable row level security;
alter table public.notifications enable row level security;

-- helper: is the caller an admin? (role flag in auth user_metadata)
create or replace function public.is_admin()
returns boolean language sql stable as
$$ select coalesce((auth.jwt() -> 'user_metadata' ->> 'role'), '') = 'admin' $$;

-- --- orders ---
-- anon: INSERT only, with server-side CHECKs (phone format enforced by DB too)
-- EN branch: source='en_landing' leads carry a valid email + NULL phone,
-- service edit (free-edit lead) or web (project inquiry); see
-- migration_en_leads.sql + migration_en_web_leads.sql
drop policy if exists orders_anon_insert on public.orders;
create policy orders_anon_insert on public.orders
  for insert to anon
  with check (
    char_length(name) between 2 and 80
    and char_length(description) between 5 and 2000
    and service in ('edit', 'web', 'pc')
    and (
      (source = 'fa_site' and phone ~ '^09[0-9]{9}$')
      or (source = 'en_landing' and service in ('edit', 'web') and phone is null
          and email ~ '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')
    )
  );

-- anon: read ONLY their own order, scoped by the unguessable track token
-- (client sends header "x-track-token: <uuid>")
drop policy if exists orders_track_own on public.orders;
create policy orders_track_own on public.orders
  for select to anon
  using (
    track_token::text =
    nullif((current_setting('request.headers', true)::json ->> 'x-track-token'), '')
  );

-- admin (authenticated + role=admin): full access
drop policy if exists orders_admin_all on public.orders;
create policy orders_admin_all on public.orders
  for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

-- --- site_content ---
-- anon: read only (pages fetch dynamic overrides; anon can NEVER write)
drop policy if exists site_content_anon_read on public.site_content;
create policy site_content_anon_read on public.site_content
  for select to anon using (true);

-- admin: full access
drop policy if exists site_content_admin_all on public.site_content;
create policy site_content_admin_all on public.site_content
  for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

-- --- notifications ---
-- admin: full access (edge functions use service_role and bypass RLS)
drop policy if exists notifications_admin_all on public.notifications;
create policy notifications_admin_all on public.notifications
  for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

-- ============================================================
-- Realtime: instant order delivery to admin panel + live tracking
-- (On Supabase Cloud these tables are usually already in the
-- publication; the statements below are idempotent-safe.)
-- ============================================================
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    begin
      alter publication supabase_realtime add table public.orders;
    exception when duplicate_object then null;
    end;
    begin
      alter publication supabase_realtime add table public.notifications;
    exception when duplicate_object then null;
    end;
    -- portfolio_items is created LATER in this file: guard so a fresh
    -- install does not die with 42P01 (relation does not exist)
    if to_regclass('public.portfolio_items') is not null then
      begin
        alter publication supabase_realtime add table public.portfolio_items;
      exception when duplicate_object then null;
      end;
    end if;
  end if;
end $$;

-- keep updated_at fresh
create or replace function public.touch_updated_at()
returns trigger language plpgsql as
$$ begin new.updated_at = now(); return new; end $$;

drop trigger if exists site_content_touch on public.site_content;
create trigger site_content_touch
  before update on public.site_content
  for each row execute function public.touch_updated_at();

-- ============================================================
-- portfolio showcase: admin-managed work samples (EN + FA pages)
-- public reads visible only; admin full via role flag; uploads go
-- to the public 'portfolio' storage bucket (see migration file)
-- ============================================================
create table if not exists public.portfolio_items (
  id         bigint generated always as identity primary key,
  created_at timestamptz not null default now(),
  page       text not null default 'en' check (page in ('en', 'fa')),
  title      text not null check (char_length(title) between 2 and 120),
  caption    text check (caption is null or char_length(caption) <= 500),
  thumb_url  text,
  video_url  text,
  sort       int not null default 0,
  visible    boolean not null default true
);
create index if not exists portfolio_page_idx on public.portfolio_items (page, sort, id);

alter table public.portfolio_items enable row level security;

drop policy if exists portfolio_public_read on public.portfolio_items;
create policy portfolio_public_read on public.portfolio_items
  for select to anon using (visible = true);

drop policy if exists portfolio_admin_all on public.portfolio_items;
create policy portfolio_admin_all on public.portfolio_items
  for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

-- portfolio_items -> realtime (table exists now; idempotent)
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    begin
      alter publication supabase_realtime add table public.portfolio_items;
    exception when duplicate_object then null;
    end;
  end if;
end $$;

-- ============================================================
-- live chat (/callme/): visitor <-> owner via dedicated bot
-- visitor sends via chat-send edge fn; owner replies in Telegram
-- (Reply to the #chat-<visitor> message); delivery is Realtime,
-- DB is history (offline visitors sync missed messages on return)
-- ============================================================
create table if not exists public.chat_messages (
  id         bigint generated always as identity primary key,
  created_at timestamptz not null default now(),
  visitor_id text not null check (visitor_id ~ '^[0-9a-f]{8,32}$'),
  sender     text not null check (sender in ('visitor', 'owner')),
  text       text not null check (char_length(text) between 1 and 2000),
  source_ip  text
);
create index if not exists chat_visitor_idx on public.chat_messages (visitor_id, id);

alter table public.chat_messages enable row level security;

-- anon: INSERT visitor messages only (edge fn validates + notifies)
drop policy if exists chat_anon_insert on public.chat_messages;
create policy chat_anon_insert on public.chat_messages
  for insert to anon
  with check (
    sender = 'visitor'
    and visitor_id ~ '^[0-9a-f]{8,32}$'
    and char_length(text) between 1 and 2000
  );

-- anon: read ONLY own thread, scoped by visitor id
-- (client sends header "x-visitor-id: <id>")
drop policy if exists chat_track_own on public.chat_messages;
create policy chat_track_own on public.chat_messages
  for select to anon
  using (
    visitor_id =
    nullif((current_setting('request.headers', true)::json ->> 'x-visitor-id'), '')
  );

-- admin (authenticated + role=admin): full access
drop policy if exists chat_admin_all on public.chat_messages;
create policy chat_admin_all on public.chat_messages
  for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    begin
      alter publication supabase_realtime add table public.chat_messages;
    exception when duplicate_object then null;
    end;
  end if;
end $$;

-- =====================================================================
-- 2/6  seed: business, services and per-page content defaults
-- source: supabase/seed.sql
-- =====================================================================
-- ============================================================

-- amirlwf.ir — seed data (run AFTER schema.sql)

-- Contact values are placeholders: edit them in /admin/ later.

-- Keys: business, services, en_home, fa_home, fa_edit, fa_web, fa_pc

-- ============================================================



insert into public.site_content (key, value) values

('business', '{

  "name": "Amir Reza Lotfi | Short-Form Video Editor",

  "owner": "Amir Reza Lotfi",

  "city": "Hashtgerd",

  "area_served": ["Worldwide (remote)", "Hashtgerd", "Karaj", "Tehran"],

  "hours": "Sat–Thu, 9:00–21:00",

  "phone": "09000000000",

  "email": "CHANGE_ME",

  "telegram": "CHANGE_ME",

  "whatsapp": "9000000000",

  "rubika": "CHANGE_ME",

  "linkedin": "CHANGE_ME",

  "youtube": "CHANGE_ME",

  "channels_enabled": {"phone": true, "email": false, "telegram": true, "whatsapp": true, "rubika": false, "linkedin": false, "youtube": false},

  "page_channels": {

    "en": {"phone": false, "email": true, "telegram": true, "whatsapp": true, "rubika": false, "linkedin": true, "youtube": true},

    "fa": {"phone": true, "email": false, "telegram": true, "whatsapp": true, "rubika": true, "linkedin": false, "youtube": false},

    "fa_edit": {"phone": true, "email": false, "telegram": true, "whatsapp": true, "rubika": true, "linkedin": false, "youtube": false},

    "fa_web": {"phone": true, "email": false, "telegram": true, "whatsapp": true, "rubika": true, "linkedin": false, "youtube": false},

    "fa_pc": {"phone": true, "email": false, "telegram": true, "whatsapp": true, "rubika": true, "linkedin": false, "youtube": false}

  }

}'::jsonb),

('services', '{

  "edit": {"title": "ادیت ویدیو", "tagline": "تدوین حرفه‌ای ویدیو برای یوتیوب، اینستاگرام و تبلیغات",

    "price_note": "قیمت توافقی بر اساس حجم پروژه؛ برای برآورد دقیق سفارش ثبت کنید.",

    "subservices": ["تدوین ویدیوی یوتیوب", "ادیت ریلز و استوری اینستاگرام", "تیزر تبلیغاتی", "زیرنویس و کپشن فارسی", "اصلاح رنگ و نور"]},

  "web": {"title": "طراحی سایت", "tagline": "طراحی سایت سریع، سئو‌محور و مقرون‌به‌صرفه",

    "price_note": "سایت معرفی از قیمت پایه توافقی؛ فروشگاه اینترنتی و امکانات خاص جداگانه برآورد می‌شود.",

    "subservices": ["سایت شرکتی و معرفی", "فروشگاه اینترنتی", "لندینگ‌پیج تبلیغاتی", "سئوی پایه و افزایش سرعت", "پشتیبانی و نگهداری"]},

  "pc": {"title": "خدمات کامپیوتری", "tagline": "نصب ویندوز، پرینتر و افزایش سرعت در محل",

    "price_note": "هزینه خدمات حضوری در هشتگرد و حومه ثابت؛ ایاب‌وذهاب برای خارج از محدوده توافقی است.",

    "subservices": ["نصب ویندوز", "نصب پرینتر", "عیب‌یابی پرینتر", "افزایش سرعت سیستم", "بکاپ و بازیابی اطلاعات"]}

}'::jsonb),

('en_home', '{

  "brand_name": "Amir Reza Lotfi",

  "footer_tagline": "Short-form video editor.",

  "seo_title": "Amir Reza Lotfi | Short-Form Video Editor — Get 1 Free Edit",

  "seo_description": "Amir Reza Lotfi — short-form video editor for Reels, TikTok and Shorts. Get your first reel edited FREE in 48 hours, no commitment.",

  "hero_eyebrow": "Short-form editing for creators",

  "hero_title": "I Edit Scroll-Stopping Shorts",

  "hero_lead": "I’m Amir Reza Lotfi. Reels, TikToks and Shorts cut for retention — strong hooks, punchy captions, clean sound. Try me free before you pay a cent.",

  "hero_cta_primary": "Get 1 Free Edit",

  "hero_cta_secondary": "See Samples",

  "hero_micro": "First reel FREE · 48-hour delivery · No commitment",

  "splash_kicker": "SHOWREEL · 2026",

  "splash_title": "",

  "splash_sub": "Short-Form Video Editor",

  "splash_cta": "Enter",

  "work_title": "Recent Work",

  "work_sub": "Real cuts, real retention — tap any piece to watch the style.",

  "offer_title": "Your First Reel Is FREE",

  "offer_sub": "One full edit, on the house — so you can judge my work on your own footage, not promises.",

  "offer_points": ["One short edited end-to-end, free", "Delivered within 48 hours", "No commitment — keep it either way", "Limited free spots each week"],

  "offer_cta": "Claim My Free Edit",

  "services_title": "What I Do",

  "services_sub": "Short-form first. Every cut is built for watch time and replays.",

  "services": [

    {"icon": "🎬", "title": "Shorts / Reels / TikTok Editing", "text": "Cuts, zooms, b-roll and sound design paced for retention on every platform."},

    {"icon": "⚡", "title": "Hooks, Captions & Pacing", "text": "Opening hooks that stop the scroll and animated captions timed to the beat."},

    {"icon": "🎨", "title": "Color, Sound & Cleanup", "text": "Balanced grade, leveled dialogue, filler-word removal and clean exports."}

  ],

  "steps_title": "How It Works",

  "steps_sub": "Three steps, no calls required.",

  "steps": [

    {"title": "Send your raw clip", "text": "Drop a link to your footage plus a short note about the style you want."},

    {"title": "Get your free edit in 48h", "text": "I cut, caption and polish one short and send it back within two days."},

    {"title": "Scale if you love it", "text": "Like the result? We set up a simple per-video flow for the rest of your content."}

  ],

  "faq_title": "Questions, Answered",

  "faq_sub": "Short answers, no fine print.",

  "faq": [

    {"q": "What do I get for free?", "a": "One short-form video edited from your raw clip — hooks, captions, pacing, color and sound — delivered in 48 hours."},

    {"q": "Is there really no commitment?", "a": "None. The free edit is yours to keep whatever you decide. If you love it, we talk about ongoing work."},

    {"q": "What should I send?", "a": "A link to your raw footage (Drive, Dropbox or unlisted YouTube) and a short note about your style or a reference you like."}

  ],

  "form_title": "Get Your Free Edit",

  "form_sub": "Fill this in — I review every request personally and reply soon."

}'::jsonb),

('fa_home', '{

  "seo_title": "امیررضا لطفی | خدمات کامپیوتر و طراحی سایت در هشتگرد",

  "seo_description": "امیررضا لطفی (امیر): ادیت ویدیو، طراحی سایت ارزان و نصب ویندوز و پرینتر در محل در هشتگرد و حومه. ثبت سفارش آنلاین با پیگیری زنده.",

  "hero_title": "امیررضا لطفی — خدمات کامپیوتر، طراحی سایت و ادیت ویدیو در هشتگرد",

  "hero_lead": "نصب ویندوز و پرینتر در محل، طراحی سایت سریع و مقرون‌به‌صرفه، و تدوین حرفه‌ای ویدیو — با ثبت سفارش آنلاین و پیگیری لحظه‌ای وضعیت کار.",

  "hero_cta_primary": "ثبت سفارش",

  "hero_cta_secondary": "گفت‌وگوی زنده",

  "card_edit_title": "ادیت ویدیو",

  "card_edit_text": "تدوین حرفه‌ای ویدیو برای یوتیوب، اینستاگرام و تبلیغات؛ زیرنویس فارسی، اصلاح رنگ و ریتم مناسب هر پلتفرم.",

  "card_web_title": "طراحی سایت",

  "card_web_text": "سایت شرکتی، فروشگاهی و لندینگ‌پیج؛ سریع، سئومحور و واکنش‌گرا، با پشتیبانی بعد از تحویل.",

  "card_pc_title": "خدمات کامپیوتری",

  "card_pc_text": "نصب ویندوز، نصب و عیب‌یابی پرینتر، افزایش سرعت سیستم و بکاپ اطلاعات — در محل شما در هشتگرد و حومه.",

  "faq_title": "سوالات پرتکرار",

  "faq": [
    {"q": "امیررضا لطفی کیست؟", "a": "امیررضا لطفی (با نام کوتاه امیر) متخصص خدمات کامپیوتر در هشتگرد است: نصب ویندوز و پرینتر در محل، طراحی سایت ارزان و سئومحور، و تدوین حرفه‌ای ویدیو برای یوتیوب، ریلز اینستاگرام و تبلیغات — با ثبت سفارش آنلاین و پیگیری زنده."},

    {"q": "چطور سفارش ثبت کنم؟", "a": "فرم ثبت سفارش همین صفحه را با نام و شماره موبایل پر کنید؛ وضعیت سفارش را به‌صورت زنده همین‌جا دنبال می‌کنید."},

    {"q": "چرا شماره موبایل لازم است؟", "a": "شماره موبایل کلید پیگیری سفارش شماست و اطلاع‌رسانی وضعیت کار از طریق آن انجام می‌شود. بدون شماره معتبر امکان ثبت سفارش نیست."},

    {"q": "در چه مناطقی خدمات حضوری دارید؟", "a": "هشتگرد، نظرآباد و ساوجبلاغ. خدمات آنلاین مثل طراحی سایت و ادیت ویدیو بدون محدودیت مکانی انجام می‌شود."},

    {"q": "ساعات کاری چیست؟", "a": "شنبه تا پنجشنبه، ۹ صبح تا ۹ شب."}

  ],

  "form_title": "ثبت سفارش"

}'::jsonb),

('fa_edit', '{

  "seo_title": "ادیت ویدیو حرفه‌ای | تدوین یوتیوب و ریلز | امیررضا لطفی",

  "seo_description": "تدوین حرفه‌ای ویدیو توسط امیررضا لطفی؛ یوتیوب، ریلز اینستاگرام و تیزر تبلیغاتی با زیرنویس فارسی و اصلاح رنگ. سفارش آنلاین با تحویل منظم.",

  "hero_title": "ادیت ویدیو حرفه‌ای",

  "intro_title": "ادیت یعنی نگه داشتن مخاطب",

  "intro_text": "فرق ویدیویی که تا آخر دیده می‌شود با ویدیویی که بعد از سه ثانیه بسته می‌شود، معمولاً تصویربرداری نیست؛ تدوین است. ریتم کات‌ها، حذف مکث‌های اضافه، زیرنویس خوانا، موسیقی‌ای که حواس را پرت نکند و اصلاح رنگی که حس حرفه‌ای بدهد — این‌ها چیزی است که من روی هر پروژه اعمال می‌کنم.",

  "price_title": "راهنمای هزینه",

  "price_note2": "قاعده سرانگشتی: ریلز کوتاه زیر یک دقیقه ارزان‌ترین است؛ ویدیوی یوتیوب بر اساس دقیقه نهایی و حجم فایل خام محاسبه می‌شود؛ تیزر تبلیغاتی با سناریو و موشن‌گرافی ساده رده میانی است. زیرنویس فارسی و اصلاح رنگ روی همه پروژه‌ها استاندارد و رایگان است. برای برآورد دقیق، در فرم سفارش بنویسید ویدیو چند دقیقه است و برای کجاست — جواب سریع می‌گیرید.",

  "subsvc_title": "زیرخدمت‌ها",

  "subservices": [

    {"title": "📺 تدوین ویدیوی یوتیوب", "text": "کات تمیز، حذف سکوت‌ها، زیرنویس، افکت‌های صوتی و تصویری به‌جا و کاور هماهنگ؛ با ساختاری که نرخ نگه‌داشت مخاطب را بالا می‌برد."},

    {"title": "📱 ادیت ریلز و استوری اینستاگرام", "text": "ابعاد عمودی، کپشن‌های بزرگ و خوانا، ترندهای صوتی و کات‌های سریع مخصوص اکسپلور؛ مناسب پیج‌های فروشگاهی و شخصی."},

    {"title": "✨ تیزر تبلیغاتی", "text": "معرفی کوتاه و اثرگذار محصول یا خدمات شما برای اینستاگرام و سایت؛ با سناریوی ساده، موشن‌متن و دعوت به اقدام شفاف."},

    {"title": "💬 زیرنویس و کپشن فارسی", "text": "زیرنویس دقیق و هماهنگ با گفتار برای ویدیوهای آماده شما؛ با فونت و استایل مناسب هر پلتفرم. بیشتر بازدید اینستاگرام بی‌صداست — زیرنویس یعنی دیده شدن."},

    {"title": "🎨 اصلاح رنگ و نور", "text": "یکدست‌سازی رنگ چند نما، اصلاح نور کم و حال‌وهوای سینمایی برای ویدیوهای آماده؛ بدون نیاز به تدوین مجدد."}

  ],

  "cta_0": "سفارش تدوین",

  "cta_1": "سفارش ریلز",

  "cta_2": "سفارش تیزر",

  "cta_3": "سفارش زیرنویس",

  "cta_4": "سفارش اصلاح رنگ",

  "faq_title": "سوالات پرتکرار",

  "faq": [

    {"q": "فایل خام را چطور ارسال کنم؟", "a": "لینک گوگل‌درایو، تلگرام یا هر فضای ابری دیگری کافی است؛ حجم بالا هم مشکلی نیست."},

    {"q": "چند دور اصلاحیه دارم؟", "a": "دو دور اصلاحیه جزئی روی هر پروژه لحاظ است تا خروجی دقیقاً همان شود که می‌خواهید."},

    {"q": "زمان تحویل ویدیو چقدر است؟", "a": "ریلز کوتاه ۲ تا ۴ روز، ویدیوی یوتیوب متوسط حدود یک هفته؛ پروژه فوری را موقع سفارش بگویید تا سریع‌تر هماهنگ کنیم."},

    {"q": "موسیقی ویدیو از کجاست؟", "a": "از آرشیو موسیقی بدون کپی‌رایت استفاده می‌کنم تا ویدیوی یوتیوب شما دچار مشکل نشود."}

  ],

  "more_title": "سایر خدمات",

  "form_title": "ثبت سفارش ادیت ویدیو"

}'::jsonb),

('fa_web', '{

  "seo_title": "طراحی سایت ارزان و سئومحور | امیررضا لطفی",

  "seo_description": "طراحی سایت شرکتی، فروشگاهی و لندینگ‌پیج توسط امیررضا لطفی؛ سریع، واکنش‌گرا و سئومحور با پشتیبانی بعد از تحویل. مشاوره و برآورد رایگان.",

  "hero_title": "طراحی سایت ارزان و سئومحور",

  "intro_title": "چرا سایت از من؟",

  "price_title": "راهنمای هزینه",

  "price_note2": "قاعده سرانگشتی: لندینگ‌پیج تک‌صفحه‌ای برای کمپین تبلیغاتی ارزان‌ترین گزینه است؛ سایت معرفی چندصفحه‌ای با بخش خدمات، نمونه‌کار و تماس در رده میانی؛ فروشگاه اینترنتی با درگاه پرداخت و پنل مدیریت بالاترین رده است. سئوی پایه (متاتگ‌ها، نقشه سایت، سرعت) روی همه پلن‌ها رایگان است. برای برآورد دقیق، فرم سفارش را با توضیح کسب‌وکارتان پر کنید — مشاوره و برآورد رایگان است.",

  "subsvc_title": "زیرخدمت‌ها",

  "subservices": [

    {"title": "🏢 سایت شرکتی و معرفی", "text": "معرفی کسب‌وکار، خدمات، نمونه‌کارها و راه‌های تماس؛ چندصفحه‌ای، فارسی و راست‌چین، با فرم تماس و دکمه‌های شبکه‌های اجتماعی."},

    {"title": "🛒 فروشگاه اینترنتی", "text": "کاتالوگ محصولات، سبد خرید، درگاه پرداخت آنلاین و پنل مدیریت سفارش‌ها؛ با آموزش کامل کار با فروشگاه بعد از تحویل."},

    {"title": "🎯 لندینگ‌پیج تبلیغاتی", "text": "صفحه فرود تک‌صفحه‌ای برای کمپین اینستاگرام یا گوگل‌ادز؛ متمرکز بر یک هدف (تماس، ثبت‌نام، خرید) و بهینه برای موبایل."},

    {"title": "📈 سئوی پایه و افزایش سرعت", "text": "برای سایتی که از قبل دارید: اصلاح متاتگ‌ها، ساختار هدینگ، فشرده‌سازی تصاویر، نقشه سایت و داده ساخت‌یافته — همان چیزهایی که رتبه گوگل را بالا می‌برد."},

    {"title": "🛠️ پشتیبانی و نگهداری", "text": "به‌روزرسانی، بکاپ منظم، رفع ایراد و تغییرات کوچک محتوایی به‌صورت ماهانه؛ تا سایت همیشه سالم و به‌روز بماند."}

  ],

  "cta_0": "سفارش سایت معرفی",

  "cta_1": "سفارش فروشگاه",

  "cta_2": "سفارش لندینگ",

  "cta_3": "سفارش سئو",

  "cta_4": "سفارش پشتیبانی",

  "faq_title": "سوالات پرتکرار",

  "faq": [

    {"q": "سایت با چه ابزاری ساخته می‌شود؟", "a": "بسته به نیاز شما: سایت سبک و سریع با کدنویسی مستقیم (مثل همین سایت)، یا وردپرس برای مدیریت آسان محتوا توسط خودتان. موقع سفارش راهنمایی‌تان می‌کنم کدام بهتر است."},

    {"q": "دامنه و هاست با کیست؟", "a": "دامنه و هاست به نام خودتان خریده می‌شود تا مالکیت کامل داشته باشید؛ من در انتخاب و اتصال آن کمک می‌کنم."},

    {"q": "زمان تحویل چقدر است؟", "a": "لندینگ‌پیج حدود یک هفته، سایت معرفی دو تا سه هفته، و فروشگاه اینترنتی بسته به امکانات سه تا شش هفته."},

    {"q": "پشتیبانی بعد از تحویل دارید؟", "a": "بله؛ رفع ایرادهای احتمالی و آموزش مدیریت سایت رایگان است و نگهداری ماهانه جداگانه توافق می‌شود."}

  ],

  "more_title": "سایر خدمات",

  "form_title": "ثبت سفارش طراحی سایت"

}'::jsonb),

('fa_pc', '{

  "seo_title": "خدمات کامپیوتر در هشتگرد | امیررضا لطفی",

  "seo_description": "نصب ویندوز، نصب و عیب‌یابی پرینتر و افزایش سرعت سیستم توسط امیررضا لطفی در محل شما در هشتگرد و حومه. ثبت سفارش آنلاین.",

  "hero_title": "خدمات کامپیوتر در هشتگرد",

  "intro_title": "چه کارهایی انجام می‌شود؟",

  "price_title": "راهنمای هزینه",

  "price_note2": "قاعده کلی: نصب ویندوز همراه با درایورها و نرم‌افزارهای پایه یک تعرفه دارد؛ نصب پرینتر و اتصال آن به چند سیستم تعرفه جداگانه؛ عیب‌یابی (گیر کاغذ، خطای درایور، مشکلات شبکه پرینتر) بر اساس زمان صرف‌شده؛ و بهینه‌سازی سرعت سیستم معمولاً در همان یک جلسه اول نتیجه محسوس می‌دهد. برآورد دقیق را بعد از ثبت سفارش و شنیدن شرح مشکل اعلام می‌کنم — بدون هزینه پنهان.",

  "subsvc_title": "زیرخدمت‌ها",

  "subservices": [

    {"title": "🪟 نصب ویندوز", "text": "نصب تمیز ویندوز ۱۰ یا ۱۱ همراه با درایورها، فعال‌سازی، نرم‌افزارهای کاربردی (مرورگر، آفیس، پخش‌کننده، آنتی‌ویروس) و بکاپ‌گیری از فایل‌های مهم قبل از نصب. درایوهای دیگر شما دست نمی‌خورد."},

    {"title": "🖨️ نصب پرینتر", "text": "نصب و راه‌اندازی پرینترهای HP، Canon، Epson و Brother؛ اتصال با کابل یا وای‌فای، نصب روی چند سیستم، و تست چاپ و اسکن جلوی چشم شما."},

    {"title": "🔧 عیب‌یابی پرینتر", "text": "رفع گیر کردن کاغذ، خطاهای درایور، چاپ نصفه‌نیمه یا بی‌کیفیت، و مشکلات اتصال پرینتر به شبکه. اگر مشکل سخت‌افزاری جدی باشد، صادقانه می‌گویم تعمیر به‌صرفه نیست."},

    {"title": "⚡ افزایش سرعت سیستم", "text": "پاک‌سازی برنامه‌های اضافه استارت‌آپ، حذف بدافزار و تبلیغ‌افزار، بهینه‌سازی تنظیمات ویندوز، و بررسی سلامت هارد. اگر سیستم قدیمی باشد، پیشنهاد دقیق ارتقا (SSD یا رم) با برآورد هزینه می‌دهم."},

    {"title": "💾 بکاپ و بازیابی اطلاعات", "text": "بکاپ‌گیری منظم از عکس‌ها و اسناد مهم روی فلش، هارد اکسترنال یا فضای ابری، و تلاش برای بازیابی فایل‌های پاک‌شده. پیشگیری همیشه ارزان‌تر از بازیابی است."}

  ],

  "cta_0": "سفارش نصب ویندوز",

  "cta_1": "سفارش نصب پرینتر",

  "cta_2": "سفارش عیب‌یابی",

  "cta_3": "سفارش افزایش سرعت",

  "cta_4": "سفارش بکاپ",

  "faq_title": "سوالات پرتکرار",

  "faq": [

    {"q": "نصب ویندوز با حفظ اطلاعات انجام می‌شود؟", "a": "بله؛ قبل از نصب از فایل‌های مهم بکاپ گرفته می‌شود و درایوهای دیگر دست نمی‌خورد. فقط حتماً در توضیح سفارش بنویسید چه فایل‌هایی مهم است."},

    {"q": "کدام مدل‌های پرینتر پشتیبانی می‌شود؟", "a": "پرینترهای خانگی و اداری HP، Canon، Epson و Brother — هم نصب اولیه و هم رفع گیر کاغذ و خطای درایور."},

    {"q": "سیستم خیلی قدیمی ارزش ارتقا دارد؟", "a": "بسته به مدل دارد؛ معمولاً اضافه کردن SSD به لپ‌تاپ‌های بالای ۸ سال هم جان تازه می‌دهد. موقع سفارش مدل سیستم را بنویسید تا بگویم به‌صرفه است یا نه."},

    {"q": "هزینه ایاب‌وذهاب چقدر است؟", "a": "داخل هشتگرد رایگان است؛ خارج از محدوده قبل از اعزام اعلام و توافق می‌شود."}

  ],

  "more_title": "سایر خدمات",

  "form_title": "ثبت سفارش خدمات کامپیوتری"

}'::jsonb)

on conflict (key) do update set value = excluded.value;



-- ============================================================

-- Grant the admin flag to your login user (run AFTER creating the

-- user in Dashboard > Authentication > Users, or via sign-up):

-- ============================================================

-- update auth.users

-- set raw_user_meta_data = coalesce(raw_user_meta_data, '{}'::jsonb) || '{"role":"admin"}'::jsonb

-- where email = 'YOUR_ADMIN_EMAIL';

-- =====================================================================
-- 3/6  portfolio storage bucket + RLS
-- source: supabase/migration_portfolio.sql
-- =====================================================================
-- ============================================================
-- Migration: portfolio showcase (run ONCE in Dashboard > SQL Editor)
-- Table portfolio_items + public 'portfolio' storage bucket + RLS.
-- Admin (service_role / role=admin) manages; public reads visible only.
-- Idempotent-safe: re-running is harmless.
-- ============================================================

create table if not exists public.portfolio_items (
  id         bigint generated always as identity primary key,
  created_at timestamptz not null default now(),
  page       text not null default 'en' check (page in ('en', 'fa')),
  title      text not null check (char_length(title) between 2 and 120),
  caption    text check (caption is null or char_length(caption) <= 500),
  thumb_url  text,
  video_url  text,
  sort       int not null default 0,
  visible    boolean not null default true
);
create index if not exists portfolio_page_idx on public.portfolio_items (page, sort, id);

alter table public.portfolio_items enable row level security;

drop policy if exists portfolio_public_read on public.portfolio_items;
create policy portfolio_public_read on public.portfolio_items
  for select to anon using (visible = true);

drop policy if exists portfolio_admin_all on public.portfolio_items;
create policy portfolio_admin_all on public.portfolio_items
  for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

-- public bucket (create if missing) + open read, admin write
insert into storage.buckets (id, name, public)
values ('portfolio', 'portfolio', true)
on conflict (id) do update set public = true;

drop policy if exists portfolio_bucket_read on storage.objects;
create policy portfolio_bucket_read on storage.objects
  for select to anon using (bucket_id = 'portfolio');

drop policy if exists portfolio_bucket_write on storage.objects;
create policy portfolio_bucket_write on storage.objects
  for all to authenticated
  using (bucket_id = 'portfolio' and public.is_admin())
  with check (bucket_id = 'portfolio' and public.is_admin());

-- realtime: new portfolio rows appear in admin instantly
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    begin
      alter publication supabase_realtime add table public.portfolio_items;
    exception when duplicate_object then null;
    end;
  end if;
end $$;

-- =====================================================================
-- 4/6  richer per-page content + page_channels
-- source: supabase/migration_page_content.sql
-- =====================================================================
-- ============================================================
-- amirlwf.ir — migration: per-page content + per-page channels
-- Run AFTER seed.sql on an existing DB (idempotent-safe).
-- New page keys: fa_edit, fa_web, fa_pc (+ richer fa_home/en_home).
-- New: business.page_channels.{en,fa,fa_edit,fa_web,fa_pc} toggles.
-- ============================================================

-- ---------- 1. business.page_channels (inherit legacy toggles) ----------
update public.site_content
set value = value || jsonb_build_object(
  'page_channels',
  jsonb_build_object(
    'en',      coalesce(value->'channels_enabled', '{"phone":false,"email":true,"telegram":true,"whatsapp":true,"rubika":false,"linkedin":true,"youtube":true}'::jsonb),
    'fa',      coalesce(value->'channels_enabled', '{"phone":true,"email":false,"telegram":true,"whatsapp":true,"rubika":true,"linkedin":false,"youtube":false}'::jsonb),
    'fa_edit', coalesce(value->'channels_enabled', '{"phone":true,"email":false,"telegram":true,"whatsapp":true,"rubika":true,"linkedin":false,"youtube":false}'::jsonb),
    'fa_web',  coalesce(value->'channels_enabled', '{"phone":true,"email":false,"telegram":true,"whatsapp":true,"rubika":true,"linkedin":false,"youtube":false}'::jsonb),
    'fa_pc',   coalesce(value->'channels_enabled', '{"phone":true,"email":false,"telegram":true,"whatsapp":true,"rubika":true,"linkedin":false,"youtube":false}'::jsonb)
  )
)
where key = 'business'
  and not (value ? 'page_channels');

-- ---------- 2. en_home: seo + brand/footer defaults (keep existing texts) ----------
update public.site_content
set value = value
  || '{"brand_name":"Amir Reza Lotfi"}'::jsonb
  || '{"footer_tagline":"Short-form video editor."}'::jsonb
  || '{"seo_title":"Amir Reza Lotfi | Short-Form Video Editor — Get 1 Free Edit"}'::jsonb
  || '{"seo_description":"Short-form video editor for Reels, TikTok and Shorts. Get your first reel edited FREE in 48 hours — no commitment."}'::jsonb
where key = 'en_home'
  and not (value ? 'seo_title');

-- ---------- 3. fa_home: seo + cards + faq + form defaults (keep existing texts) ----------
update public.site_content
set value = value
  || '{"seo_title":"امیررضا لطفی | خدمات کامپیوتر و طراحی سایت در هشتگرد"}'::jsonb
  || '{"seo_description":"امیررضا لطفی (امیر): ادیت ویدیو، طراحی سایت ارزان و نصب ویندوز و پرینتر در محل در هشتگرد و حومه. ثبت سفارش آنلاین با پیگیری زنده."}'::jsonb
  || '{"card_edit_title":"ادیت ویدیو"}'::jsonb
  || '{"card_edit_text":"تدوین حرفه‌ای ویدیو برای یوتیوب، اینستاگرام و تبلیغات؛ زیرنویس فارسی، اصلاح رنگ و ریتم مناسب هر پلتفرم."}'::jsonb
  || '{"card_web_title":"طراحی سایت"}'::jsonb
  || '{"card_web_text":"سایت شرکتی، فروشگاهی و لندینگ‌پیج؛ سریع، سئومحور و واکنش‌گرا، با پشتیبانی بعد از تحویل."}'::jsonb
  || '{"card_pc_title":"خدمات کامپیوتری"}'::jsonb
  || '{"card_pc_text":"نصب ویندوز، نصب و عیب‌یابی پرینتر، افزایش سرعت سیستم و بکاپ اطلاعات — در محل شما در هشتگرد و حومه."}'::jsonb
  || '{"faq_title":"سوالات پرتکرار"}'::jsonb
  || '{"form_title":"ثبت سفارش"}'::jsonb
where key = 'fa_home'
  and not (value ? 'seo_title');

-- fa_home.faq: only when missing (admin edits win otherwise)
update public.site_content
set value = value || '{
  "faq": [
    {"q": "چطور سفارش ثبت کنم؟", "a": "فرم ثبت سفارش همین صفحه را با نام و شماره موبایل پر کنید؛ وضعیت سفارش را به‌صورت زنده همین‌جا دنبال می‌کنید."},
    {"q": "چرا شماره موبایل لازم است؟", "a": "شماره موبایل کلید پیگیری سفارش شماست و اطلاع‌رسانی وضعیت کار از طریق آن انجام می‌شود. بدون شماره معتبر امکان ثبت سفارش نیست."},
    {"q": "در چه مناطقی خدمات حضوری دارید؟", "a": "هشتگرد، نظرآباد و ساوجبلاغ. خدمات آنلاین مثل طراحی سایت و ادیت ویدیو بدون محدودیت مکانی انجام می‌شود."},
    {"q": "ساعات کاری چیست؟", "a": "شنبه تا پنجشنبه، ۹ صبح تا ۹ شب."}
  ]
}'::jsonb
where key = 'fa_home'
  and not (value ? 'faq');

-- ---------- 4. new service-page keys (only when missing — never overwrite admin edits) ----------
insert into public.site_content (key, value) values
('fa_edit', '{
  "seo_title": "ادیت ویدیو حرفه‌ای | تدوین یوتیوب و ریلز | امیررضا لطفی",
  "seo_description": "تدوین ویدیوی یوتیوب، ریلز اینستاگرام، تیزر تبلیغاتی و زیرنویس فارسی با اصلاح رنگ حرفه‌ای. سفارش آنلاین با تحویل منظم.",
  "hero_title": "ادیت ویدیو حرفه‌ای",
  "intro_title": "ادیت یعنی نگه داشتن مخاطب",
  "intro_text": "فرق ویدیویی که تا آخر دیده می‌شود با ویدیویی که بعد از سه ثانیه بسته می‌شود، معمولاً تصویربرداری نیست؛ تدوین است. ریتم کات‌ها، حذف مکث‌های اضافه، زیرنویس خوانا، موسیقی‌ای که حواس را پرت نکند و اصلاح رنگی که حس حرفه‌ای بدهد — این‌ها چیزی است که من روی هر پروژه اعمال می‌کنم.",
  "price_title": "راهنمای هزینه",
  "price_note2": "قاعده سرانگشتی: ریلز کوتاه زیر یک دقیقه ارزان‌ترین است؛ ویدیوی یوتیوب بر اساس دقیقه نهایی و حجم فایل خام محاسبه می‌شود؛ تیزر تبلیغاتی با سناریو و موشن‌گرافی ساده رده میانی است. زیرنویس فارسی و اصلاح رنگ روی همه پروژه‌ها استاندارد و رایگان است. برای برآورد دقیق، در فرم سفارش بنویسید ویدیو چند دقیقه است و برای کجاست — جواب سریع می‌گیرید.",
  "subsvc_title": "زیرخدمت‌ها",
  "subservices": [
    {"title": "📺 تدوین ویدیوی یوتیوب", "text": "کات تمیز، حذف سکوت‌ها، زیرنویس، افکت‌های صوتی و تصویری به‌جا و کاور هماهنگ؛ با ساختاری که نرخ نگه‌داشت مخاطب را بالا می‌برد."},
    {"title": "📱 ادیت ریلز و استوری اینستاگرام", "text": "ابعاد عمودی، کپشن‌های بزرگ و خوانا، ترندهای صوتی و کات‌های سریع مخصوص اکسپلور؛ مناسب پیج‌های فروشگاهی و شخصی."},
    {"title": "✨ تیزر تبلیغاتی", "text": "معرفی کوتاه و اثرگذار محصول یا خدمات شما برای اینستاگرام و سایت؛ با سناریوی ساده، موشن‌متن و دعوت به اقدام شفاف."},
    {"title": "💬 زیرنویس و کپشن فارسی", "text": "زیرنویس دقیق و هماهنگ با گفتار برای ویدیوهای آماده شما؛ با فونت و استایل مناسب هر پلتفرم. بیشتر بازدید اینستاگرام بی‌صداست — زیرنویس یعنی دیده شدن."},
    {"title": "🎨 اصلاح رنگ و نور", "text": "یکدست‌سازی رنگ چند نما، اصلاح نور کم و حال‌وهوای سینمایی برای ویدیوهای آماده؛ بدون نیاز به تدوین مجدد."}
  ],
  "cta_0": "سفارش تدوین",
  "cta_1": "سفارش ریلز",
  "cta_2": "سفارش تیزر",
  "cta_3": "سفارش زیرنویس",
  "cta_4": "سفارش اصلاح رنگ",
  "faq_title": "سوالات پرتکرار",
  "faq": [
    {"q": "فایل خام را چطور ارسال کنم؟", "a": "لینک گوگل‌درایو، تلگرام یا هر فضای ابری دیگری کافی است؛ حجم بالا هم مشکلی نیست."},
    {"q": "چند دور اصلاحیه دارم؟", "a": "دو دور اصلاحیه جزئی روی هر پروژه لحاظ است تا خروجی دقیقاً همان شود که می‌خواهید."},
    {"q": "زمان تحویل ویدیو چقدر است؟", "a": "ریلز کوتاه ۲ تا ۴ روز، ویدیوی یوتیوب متوسط حدود یک هفته؛ پروژه فوری را موقع سفارش بگویید تا سریع‌تر هماهنگ کنیم."},
    {"q": "موسیقی ویدیو از کجاست؟", "a": "از آرشیو موسیقی بدون کپی‌رایت استفاده می‌کنم تا ویدیوی یوتیوب شما دچار مشکل نشود."}
  ],
  "more_title": "سایر خدمات",
  "form_title": "ثبت سفارش ادیت ویدیو"
}'::jsonb),
('fa_web', '{
  "seo_title": "طراحی سایت ارزان و سئومحور | امیررضا لطفی",
  "seo_description": "طراحی سایت شرکتی، فروشگاهی و لندینگ‌پیج؛ سریع، واکنش‌گرا و سئومحور با پشتیبانی بعد از تحویل. مشاوره و برآورد رایگان.",
  "hero_title": "طراحی سایت ارزان و سئومحور",
  "intro_title": "چرا سایت از من؟",
  "price_title": "راهنمای هزینه",
  "price_note2": "قاعده سرانگشتی: لندینگ‌پیج تک‌صفحه‌ای برای کمپین تبلیغاتی ارزان‌ترین گزینه است؛ سایت معرفی چندصفحه‌ای با بخش خدمات، نمونه‌کار و تماس در رده میانی؛ فروشگاه اینترنتی با درگاه پرداخت و پنل مدیریت بالاترین رده است. سئوی پایه (متاتگ‌ها، نقشه سایت، سرعت) روی همه پلن‌ها رایگان است. برای برآورد دقیق، فرم سفارش را با توضیح کسب‌وکارتان پر کنید — مشاوره و برآورد رایگان است.",
  "subsvc_title": "زیرخدمت‌ها",
  "subservices": [
    {"title": "🏢 سایت شرکتی و معرفی", "text": "معرفی کسب‌وکار، خدمات، نمونه‌کارها و راه‌های تماس؛ چندصفحه‌ای، فارسی و راست‌چین، با فرم تماس و دکمه‌های شبکه‌های اجتماعی."},
    {"title": "🛒 فروشگاه اینترنتی", "text": "کاتالوگ محصولات، سبد خرید، درگاه پرداخت آنلاین و پنل مدیریت سفارش‌ها؛ با آموزش کامل کار با فروشگاه بعد از تحویل."},
    {"title": "🎯 لندینگ‌پیج تبلیغاتی", "text": "صفحه فرود تک‌صفحه‌ای برای کمپین اینستاگرام یا گوگل‌ادز؛ متمرکز بر یک هدف (تماس، ثبت‌نام، خرید) و بهینه برای موبایل."},
    {"title": "📈 سئوی پایه و افزایش سرعت", "text": "برای سایتی که از قبل دارید: اصلاح متاتگ‌ها، ساختار هدینگ، فشرده‌سازی تصاویر، نقشه سایت و داده ساخت‌یافته — همان چیزهایی که رتبه گوگل را بالا می‌برد."},
    {"title": "🛠️ پشتیبانی و نگهداری", "text": "به‌روزرسانی، بکاپ منظم، رفع ایراد و تغییرات کوچک محتوایی به‌صورت ماهانه؛ تا سایت همیشه سالم و به‌روز بماند."}
  ],
  "cta_0": "سفارش سایت معرفی",
  "cta_1": "سفارش فروشگاه",
  "cta_2": "سفارش لندینگ",
  "cta_3": "سفارش سئو",
  "cta_4": "سفارش پشتیبانی",
  "faq_title": "سوالات پرتکرار",
  "faq": [
    {"q": "سایت با چه ابزاری ساخته می‌شود؟", "a": "بسته به نیاز شما: سایت سبک و سریع با کدنویسی مستقیم (مثل همین سایت)، یا وردپرس برای مدیریت آسان محتوا توسط خودتان. موقع سفارش راهنمایی‌تان می‌کنم کدام بهتر است."},
    {"q": "دامنه و هاست با کیست؟", "a": "دامنه و هاست به نام خودتان خریده می‌شود تا مالکیت کامل داشته باشید؛ من در انتخاب و اتصال آن کمک می‌کنم."},
    {"q": "زمان تحویل چقدر است؟", "a": "لندینگ‌پیج حدود یک هفته، سایت معرفی دو تا سه هفته، و فروشگاه اینترنتی بسته به امکانات سه تا شش هفته."},
    {"q": "پشتیبانی بعد از تحویل دارید؟", "a": "بله؛ رفع ایرادهای احتمالی و آموزش مدیریت سایت رایگان است و نگهداری ماهانه جداگانه توافق می‌شود."}
  ],
  "more_title": "سایر خدمات",
  "form_title": "ثبت سفارش طراحی سایت"
}'::jsonb),
('fa_pc', '{
  "seo_title": "خدمات کامپیوتر در هشتگرد | امیررضا لطفی",
  "seo_description": "نصب ویندوز، نصب و عیب‌یابی پرینتر، افزایش سرعت سیستم و بکاپ اطلاعات در محل شما در هشتگرد و حومه. ثبت سفارش آنلاین.",
  "hero_title": "خدمات کامپیوتر در هشتگرد",
  "intro_title": "چه کارهایی انجام می‌شود؟",
  "price_title": "راهنمای هزینه",
  "price_note2": "قاعده کلی: نصب ویندوز همراه با درایورها و نرم‌افزارهای پایه یک تعرفه دارد؛ نصب پرینتر و اتصال آن به چند سیستم تعرفه جداگانه؛ عیب‌یابی (گیر کاغذ، خطای درایور، مشکلات شبکه پرینتر) بر اساس زمان صرف‌شده؛ و بهینه‌سازی سرعت سیستم معمولاً در همان یک جلسه اول نتیجه محسوس می‌دهد. برآورد دقیق را بعد از ثبت سفارش و شنیدن شرح مشکل اعلام می‌کنم — بدون هزینه پنهان.",
  "subsvc_title": "زیرخدمت‌ها",
  "subservices": [
    {"title": "🪟 نصب ویندوز", "text": "نصب تمیز ویندوز ۱۰ یا ۱۱ همراه با درایورها، فعال‌سازی، نرم‌افزارهای کاربردی (مرورگر، آفیس، پخش‌کننده، آنتی‌ویروس) و بکاپ‌گیری از فایل‌های مهم قبل از نصب. درایوهای دیگر شما دست نمی‌خورد."},
    {"title": "🖨️ نصب پرینتر", "text": "نصب و راه‌اندازی پرینترهای HP، Canon، Epson و Brother؛ اتصال با کابل یا وای‌فای، نصب روی چند سیستم، و تست چاپ و اسکن جلوی چشم شما."},
    {"title": "🔧 عیب‌یابی پرینتر", "text": "رفع گیر کردن کاغذ، خطاهای درایور، چاپ نصفه‌نیمه یا بی‌کیفیت، و مشکلات اتصال پرینتر به شبکه. اگر مشکل سخت‌افزاری جدی باشد، صادقانه می‌گویم تعمیر به‌صرفه نیست."},
    {"title": "⚡ افزایش سرعت سیستم", "text": "پاک‌سازی برنامه‌های اضافه استارت‌آپ، حذف بدافزار و تبلیغ‌افزار، بهینه‌سازی تنظیمات ویندوز، و بررسی سلامت هارد. اگر سیستم قدیمی باشد، پیشنهاد دقیق ارتقا (SSD یا رم) با برآورد هزینه می‌دهم."},
    {"title": "💾 بکاپ و بازیابی اطلاعات", "text": "بکاپ‌گیری منظم از عکس‌ها و اسناد مهم روی فلش، هارد اکسترنال یا فضای ابری، و تلاش برای بازیابی فایل‌های پاک‌شده. پیشگیری همیشه ارزان‌تر از بازیابی است."}
  ],
  "cta_0": "سفارش نصب ویندوز",
  "cta_1": "سفارش نصب پرینتر",
  "cta_2": "سفارش عیب‌یابی",
  "cta_3": "سفارش افزایش سرعت",
  "cta_4": "سفارش بکاپ",
  "faq_title": "سوالات پرتکرار",
  "faq": [
    {"q": "نصب ویندوز با حفظ اطلاعات انجام می‌شود؟", "a": "بله؛ قبل از نصب از فایل‌های مهم بکاپ گرفته می‌شود و درایوهای دیگر دست نمی‌خورد. فقط حتماً در توضیح سفارش بنویسید چه فایل‌هایی مهم است."},
    {"q": "کدام مدل‌های پرینتر پشتیبانی می‌شود؟", "a": "پرینترهای خانگی و اداری HP، Canon، Epson و Brother — هم نصب اولیه و هم رفع گیر کاغذ و خطای درایور."},
    {"q": "سیستم خیلی قدیمی ارزش ارتقا دارد؟", "a": "بسته به مدل دارد؛ معمولاً اضافه کردن SSD به لپ‌تاپ‌های بالای ۸ سال هم جان تازه می‌دهد. موقع سفارش مدل سیستم را بنویسید تا بگویم به‌صرفه است یا نه."},
    {"q": "هزینه ایاب‌وذهاب چقدر است؟", "a": "داخل هشتگرد رایگان است؛ خارج از محدوده قبل از اعزام اعلام و توافق می‌شود."}
  ],
  "more_title": "سایر خدمات",
  "form_title": "ثبت سفارش خدمات کامپیوتری"
}'::jsonb)
on conflict (key) do nothing;

-- =====================================================================
-- 5/6  English service-page content keys
-- source: supabase/migration_en_service_pages.sql
-- =====================================================================
-- migration_en_service_pages.sql — EN content keys for the new English
-- section (/en/services/edit.html + /en/services/web.html).
-- Idempotent: `on conflict do nothing` — never overwrites admin edits.
-- Fresh installs: run after seed.sql (schema.sql + seed.sql cover the rest).

insert into public.site_content (key, value) values
(
  'en_edit',
  '{
    "seo_title": "Video Editing | Reels, Shorts and YouTube | Amir Reza Lotfi",
    "seo_description": "Video editing by Amir Reza Lotfi: retention-first cuts for Reels, Shorts and YouTube, with captions, color and sound. First edit free.",
    "brand_name": "Amir Reza Lotfi",
    "footer_tagline": "Short-form video editor.",
    "eyebrow": "Video editing service",
    "hero_title": "Video Editing That Holds Attention",
    "hero_lead": "Reels, TikToks, Shorts and YouTube videos cut for retention — strong hooks, tight pacing, clean color and sound. Try me free before you pay.",
    "included_title": "Every Edit Ships With",
    "included_sub": "The same checklist on a 30-second Reel or a 12-minute video.",
    "included": [
      {"icon": "🪝", "title": "Hook-first structure", "text": "A first three seconds built to stop the scroll, then pattern interrupts that keep watch time climbing."},
      {"icon": "💬", "title": "Captions & subtitles", "text": "Readable, on-beat on-screen text — most feeds play muted, so captions are what actually get read."},
      {"icon": "🎞️", "title": "Pacing & b-roll", "text": "Dead air removed, cuts placed on the beat, b-roll and zooms used only where they earn attention."},
      {"icon": "🎨", "title": "Color & sound", "text": "Balanced grade across shots, leveled dialogue, music that supports instead of fights the voice."},
      {"icon": "📱", "title": "Platform-ready exports", "text": "Correct aspect ratios, safe margins and file settings for Reels, Shorts, TikTok and YouTube."},
      {"icon": "⚡", "title": "Fast turnaround", "text": "Short-form edits delivered within 48 hours, with two revision rounds included on every project."}
    ],
    "offer_title": "Your First Edit Is FREE",
    "offer_sub": "Send one raw clip. Get it back edited within 48 hours — keep it whatever you decide.",
    "steps_title": "How It Works",
    "faq_title": "Questions, Answered",
    "faq": [
      {"q": "How do I send my raw footage?", "a": "A Drive, Dropbox or unlisted YouTube link is enough — large files are fine, and a short note about your style helps."},
      {"q": "How many revision rounds do I get?", "a": "Two rounds of small revisions are included, so the final cut matches your brief without extra cost."},
      {"q": "How fast is delivery?", "a": "Short-form edits land within 48 hours. Longer YouTube videos usually take a few days, and urgent work can be scheduled."},
      {"q": "Do you write the captions?", "a": "Yes — hooks, on-screen captions and subtitles are part of the edit, styled for each platform and timed to the beat."},
      {"q": "What does paid work cost?", "a": "Per video, agreed up front based on length and complexity. The free edit exists so you can judge the result before spending anything."}
    ],
    "related_title": "Related Services",
    "form_title": "Get Your Free Edit"
  }'
),
(
  'en_web',
  '{
    "seo_title": "Web Design | Fast, SEO-Friendly Sites | Amir Reza Lotfi",
    "seo_description": "Fast, mobile-first websites and landing pages by Amir Reza Lotfi, built for speed and search, with support after launch.",
    "brand_name": "Amir Reza Lotfi",
    "footer_tagline": "Short-form video editor.",
    "eyebrow": "Web design service",
    "hero_title": "Websites Built to Load Fast and Rank",
    "hero_lead": "Clean, mobile-first sites and landing pages — light, quick and structured for search. Launched with support, not abandoned after handoff.",
    "included_title": "Every Website Ships With",
    "included_sub": "The checklist that separates a real site from a template.",
    "included": [
      {"icon": "📱", "title": "Mobile-first layout", "text": "Designed at phone width first, then scaled up — most of your visitors never see the desktop view."},
      {"icon": "⚡", "title": "Speed optimization", "text": "Lean HTML and CSS, local fonts, lazy images — fast loads improve both rankings and conversions."},
      {"icon": "🔎", "title": "On-page SEO", "text": "Unique titles and descriptions, one clear heading per page, structured data, sitemap and canonical tags."},
      {"icon": "🧭", "title": "Clear structure", "text": "Hero, services, proof, FAQ and contact — the path a visitor expects, with one obvious next step."},
      {"icon": "✍️", "title": "Content help", "text": "I shape the headlines and page flow with you, so the copy sells instead of just filling space."},
      {"icon": "🛠️", "title": "Support after launch", "text": "Edits, updates and hosting help when you need them — the site keeps working after go-live."}
    ],
    "offer_title": "Your First Short Edit Is FREE",
    "offer_sub": "Every site deserves video on it — so the first edit for your new site is on the house.",
    "steps_title": "How It Works",
    "faq_title": "Questions, Answered",
    "faq": [
      {"q": "How long does a website take?", "a": "A one-page landing site takes a few days. A multi-page business site usually takes one to two weeks, including content and revisions."},
      {"q": "Do you write the content?", "a": "I structure the pages and headlines with you, and you provide the final texts — or I can draft them from your notes."},
      {"q": "Will the site rank on Google?", "a": "Every site ships with clean HTML, unique titles and descriptions, structured data, a sitemap and fast load times — the foundations search engines need."},
      {"q": "Do you offer support after launch?", "a": "Yes — updates, small redesigns and hosting help are available as a monthly retainer or per request."}
    ],
    "related_title": "Related Services",
    "form_title": "Start Your Project"
  }'
)
on conflict (key) do nothing;

-- per-page channel toggles for the two new EN pages (mirror the EN home
-- defaults: email/telegram/whatsapp/linkedin/youtube on, phone/rubika off).
update public.site_content
set value = (
  select jsonb_set(
    coalesce(value, '{}'::jsonb),
    '{page_channels}',
    coalesce(value -> 'page_channels', '{}'::jsonb)
      || jsonb_build_object(
           'en_edit', value -> 'page_channels' -> 'en',
           'en_web',  value -> 'page_channels' -> 'en'
         )
  )
  from public.site_content sc
  where sc.key = 'business'
)
where key = 'business'
  and coalesce(value -> 'page_channels' -> 'en_edit', 'null'::jsonb) = 'null'::jsonb;

-- =====================================================================
-- 6/6  bot_config: Telegram bots managed in the admin panel
-- source: supabase/migration_bots.sql
-- =====================================================================
-- ============================================================
-- migration_bots.sql — Telegram bot credentials managed from the admin panel
-- Run ONCE in Dashboard > SQL Editor (idempotent-safe).
--
-- Three bots, each with its own token + chat id:
--   chat       -> live chat (/fa/callme/ + /callme/) notifications
--   orders_fa  -> customer info from the PERSIAN section
--   orders_en  -> customer info from the ENGLISH section
--
-- SECURITY: tokens are SECRET. anon has no access at all (revoke + RLS),
-- only the admin panel (authenticated + user_metadata.role='admin') can
-- read/write, and Edge Functions read them with service_role.
-- Env secrets (FA_BOT_TOKEN, CHAT_BOT_TOKEN …) stay as fallback, so the
-- functions keep working before the panel is filled in.
-- ============================================================

create table if not exists public.bot_config (
  id         text primary key check (id in ('chat', 'orders_fa', 'orders_en')),
  label      text not null default '',
  bot_token  text,                 -- "123456:AA..." from @BotFather
  chat_id    text,                 -- target chat (e.g. 8376494566 or -100…)
  enabled    boolean not null default false,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.bot_config enable row level security;

-- no anon/other-role access at all (belt) …
revoke all on public.bot_config from anon;
grant select, insert, update, delete on public.bot_config to authenticated;

-- … and RLS only lets the admin role (suspenders)
drop policy if exists bot_config_admin_all on public.bot_config;
create policy bot_config_admin_all on public.bot_config
  for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

-- the three bots (never overwrites a configured row)
insert into public.bot_config (id, label, enabled) values
  ('chat',      'بات گفت‌وگوی زنده',        false),
  ('orders_fa', 'بات اطلاعات مشتری (فارسی)', false),
  ('orders_en', 'بات اطلاعات مشتری (انگلیسی)', false)
on conflict (id) do nothing;

-- helpful lookup for the edge functions (no secrets exposed anywhere)
comment on table public.bot_config is
  'Telegram bot credentials (secret) readable only by admin / service_role';


-- =====================================================================
-- verification (expect non-zero counts, no errors)
-- =====================================================================
select 'tables'  as what, count(*) as n from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind = 'r'
union all
select 'site_content keys', count(*) from public.site_content
union all
select 'bot_config rows', count(*) from public.bot_config
union all
select 'portfolio_items rows', count(*) from public.portfolio_items
union all
select 'chat_messages rows', count(*) from public.chat_messages;

select id, (bot_token is not null) as has_token, chat_id, enabled
from public.bot_config order by id;
