"""build_setup_all.py — regenerate supabase/setup_all.sql from the sources.

One SQL Editor paste for a FRESH Supabase project: schema + seed + every
migration, in the exact order the README prescribes, ending with a
verification block. All parts are idempotent, so re-running after a failure
is safe.

    python tools/build_setup_all.py
"""
import io
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PARTS = [
    ("schema.sql", "1/6  schema: tables, RLS, functions, realtime"),
    ("seed.sql", "2/6  seed: business, services and per-page content defaults"),
    ("migration_portfolio.sql", "3/6  portfolio storage bucket + RLS"),
    ("migration_page_content.sql", "4/6  richer per-page content + page_channels"),
    ("migration_en_service_pages.sql", "5/6  English service-page content keys"),
    ("migration_bots.sql", "6/6  bot_config: Telegram bots managed in the admin panel"),
]
OUT = os.path.join(ROOT, "supabase", "setup_all.sql")

HEADER = """-- =====================================================================
-- setup_all.sql — ONE paste for a FRESH Supabase project (amirlwf.ir)
-- Generated by tools/build_setup_all.py — do not edit this file by hand.
--
-- Dashboard -> SQL Editor -> paste ALL of it -> Run.
-- Every part is idempotent: if a statement fails halfway, fix it and run
-- the whole file again (already-applied parts are harmless).
--
-- After this: Authentication -> Users -> create the admin account, then
-- give it the admin flag (see README step 1.4), then fill the three bots
-- in the panel and deploy the Edge Functions.
-- =====================================================================

"""

FOOTER = """
-- =====================================================================
-- verification (expect non-zero counts, no errors)
-- =====================================================================
select 'tables'  as what, count(*) as n from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind = 'r'
union all
select 'site_content keys', count(*) from public.site_content
union all
select 'bot_config rows', count(*) from public.bot_config
union all
select 'portfolio_items rows', count(*) from public.portfolio_items
union all
select 'chat_messages rows', count(*) from public.chat_messages;

select id, (bot_token is not null) as has_token, chat_id, enabled
from public.bot_config order by id;
"""


def render():
    out = [HEADER]
    for name, banner in PARTS:
        path = os.path.join(ROOT, "supabase", name)
        body = io.open(path, encoding="utf-8", newline="").read().replace("\r\n", "\n").rstrip("\n")
        out.append("-- =====================================================================\n")
        out.append("-- " + banner + "\n")
        out.append("-- source: supabase/" + name + "\n")
        out.append("-- =====================================================================\n")
        out.append(body + "\n\n")
    out.append(FOOTER)
    return "".join(out)


def main():
    text = render()
    io.open(OUT, "w", encoding="utf-8", newline="\n").write(text)
    print("wrote %s (%d lines, %d chars)" % (os.path.relpath(OUT, ROOT), text.count("\n"), len(text)))


if __name__ == "__main__":
    main()
